# Generated by Django 6.0.2 on 2026-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, choices=[('', 'No special occasion'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('date_night', 'Date Night'), ('business', 'Business Dinner'), ('celebration', 'Celebration'), ('other', 'Other')], max_length=20),
        ),
    ]
