# Generated by Django 6.0.2 on 2026-02-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
